include ../config.mk

OBJS = arch/$(ARCH)/machine/$(MACHINE)/start.o \
       arch/$(ARCH)/astart.o \
       arch/$(ARCH)/lib/atomic.o \
       arch/$(ARCH)/lib/core.o \
       arch/$(ARCH)/lib/ctx.o \
       arch/$(ARCH)/lib/interrupt.o \
       arch/$(ARCH)/lib/memswitch.o \
       arch/$(ARCH)/lib/timer.o \
       arch/$(ARCH)/lib/trampoline.o \
       lib/console.o \
       lib/devicetree.o \
       lib/exception.o \
       lib/hardware.o \
       lib/pagefault.o \
       lib/panic.o \
       lib/pmem.o \
       lib/process.o \
       lib/schedule.o \
       lib/spinlock.o \
       lib/string.o \
       lib/syscall.o \
       lib/syscall/exit.o \
       lib/syscall/fork.o \
       lib/syscall/growmem.o \
       lib/syscall/reboot.o \
       lib/syscall/shutdown.o \
       lib/timer.o \
       lib/uart.o \
       lib/vmem.o \
       src/kernel.o \
       src/kvmem.o \
       src/mem.o \
